name: group_trip_expense_splitter
description: Professional Group Trip Expense Splitter App with Real-time Collaboration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  # firebase_core: ^2.14.0
  # firebase_auth: ^4.6.3
  # cloud_firestore: ^4.8.1
  # firebase_storage: ^11.5.6
  # firebase_messaging: ^14.7.10
  flutter_hooks: ^0.18.6
  intl: ^0.18.1
  # cached_network_image: ^3.2.3
  # image_picker: ^1.0.4
  # file_picker: ^6.1.1
  # local_auth: ^2.1.7
  # shared_preferences: ^2.2.2
  # connectivity_plus: ^5.0.2
  # permission_handler: ^11.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # Additional production dependencies
  # firebase_crashlytics: ^3.4.8
  # firebase_analytics: ^10.7.4
  # firebase_performance: ^0.9.3+8
  # url_launcher: ^6.1.14
  # share_plus: ^7.2.2
  path_provider: ^2.1.4
  # image: ^4.1.3
  # csv: ^5.0.2
  # flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  uuid: ^4.5.1
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true

  # App assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # App fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
